### ISSUE TITLE
推理时 RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half

### ISSUE THREAD

**Issue by TAAANGY** [zjukg/KoPA#11]
你好，推理时，生成报如下错误，请问该如何解决？
Traceback (most recent call last):
  File "/data/sdkjualk/pymp_kopa/inference_kopa.py", line 78, in <module>
    generate_ids = model.generate(
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 1034, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/transformers/generation/utils.py", line 1538, in generate
    return self.greedy_search(
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/transformers/generation/utils.py", line 2362, in greedy_search
    outputs = self(
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 824, in forward
    logits = self.lm_head(hidden_states)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/tyy/anaconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, weight, bias)
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::Half

**Comment by Zhang-Each** [comment]
你好，导致这一问题的原因可能是peft和transformers的版本不匹配。我们在实验过程中使用的是4.28.0版本的transformers以及0.3.0版本的peft
