### ISSUE TITLE
ValueError: Target modules [q_proj,k_proj,v_proj,o_proj] not found in the base model.

### ISSUE THREAD

**Issue by 1286169349** [zjukg/KoPA#8]
请问您用的是https://huggingface.co/wxjiao/alpaca-7b这个模型吗？我在加载模型时出现了问题
Traceback (most recent call last):
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zzu_zxw/zjl_data/KoPA/finetune_kopa.py", line 178, in train
    model = get_peft_model(model, config)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/mapping.py", line 112, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 647, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 91, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/tuners/lora.py", line 131, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/tuners/lora.py", line 137, in add_adapter
    self._find_and_replace(adapter_name)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/peft/tuners/lora.py", line 222, in _find_and_replace
    raise ValueError(
ValueError: Target modules [q_proj,k_proj,v_proj,o_proj] not found in the base model. Please check the target modules and try again.
python-BaseException

进程已结束,退出代码1

**Comment by 1286169349** [comment]
已经解决了

**Comment by Guo-Chenxu** [comment]
> 已经解决了

你好, 请问一下你是怎么解决的

**Comment by Log4J-Ops** [comment]
> > 已经解决了
> 
> 你好, 请问一下你是怎么解决的

作者readme里面的配置格式写错了，你仔细和代码里对比一下target那部分，我调了一下发现引号是在里面的
