### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by 1286169349** [zjukg/KoPA#9]
请问出现下边的报错是因为transformer版本问题吗？您使用的是什么版本呢？
Traceback (most recent call last):
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zzu_zxw/zjl_data/KoPA/finetune_kopa.py", line 232, in train
    trainer = transformers.Trainer(
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 498, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 740, in _move_model_to_device
    model = model.to(device)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 7 more times]
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/zzu_zxw/miniconda3/envs/alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

进程已结束,退出代码1

**Comment by Zhang-Each** [comment]
你好，我们使用的transformers库版本是 4.28.0 torch版本是2.0.0

**Comment by chtkg** [comment]
你的这个问题NotImplementedError: Cannot copy out of meta tensor; no data! 解决了吗？我也出现了跟你一样的问题，也安装了transformers库版本 4.28.0 和torch版本2.0.0，但是还是出现这个问题。
